@startuml
'https://plantuml.com/class-diagram

class Developer {
develop()
}

class BackEndDeveloper {
develop()
writeJava()
}

class FrontEndDeveloper {
develop()
writeJavascript()
}

class Project {
implement()
}

Project ..> Developer
Developer <|-- BackEndDeveloper
Developer <|-- FrontEndDeveloper

@enduml