@startuml
'https://plantuml.com/class-diagram

interface SmartDevice {
print()
scan()
fax()
}

class AllInOnePrinter {
print()
scan()
fax()
}

class EconomicPrinter {
print()
scan() - not supported
fax() - not supported
}

SmartDevice <|-- AllInOnePrinter
SmartDevice <|-- EconomicPrinter

@enduml