@startuml
'https://plantuml.com/class-diagram


class BankingAppWithdrawalService

class Account {
deposit(BigDecimal)
}

class WithdrawableAccount {
withdraw(BigDecimal)
}

class CurrentAccount {
deposit(BigDecimal)
withdraw(BigDecimal)
}

class SavingsAccount {
deposit(BigDecimal)
withdraw(BigDecimal)
}

class FixedTermDepositAccount  {
deposit(BigDecimal)
}

Account <|-- WithdrawableAccount
WithdrawableAccount <|-- CurrentAccount
WithdrawableAccount <|-- SavingsAccount
Account <|-- FixedTermDepositAccount
WithdrawableAccount <.. BankingAppWithdrawalService

@enduml