@startuml
'https://plantuml.com/class-diagram


class BankingAppWithdrawalService

class CurrentAccount {
deposit(BigDecimal)
withdraw(BigDecimal)
}

class SavingsAccount {
deposit(BigDecimal)
withdraw(BigDecimal)
}

BankingAppWithdrawalService ..> CurrentAccount
BankingAppWithdrawalService ..> SavingsAccount

@enduml